# SYNTAX TEST "RBS.sublime-syntax"

module Hoge end
# <- keyword.declaration.module.rbs
#      ^ entity.name.class.rbs
#           ^ keyword.other.end.rbs

module Foo::Hoge[X] end
# <- keyword.declaration.module.rbs
#      ^ variable.other.namespace.rbs
#         ^ punctuation.separator.type_name.colon2.rbs
#           ^ entity.name.class.rbs
#               ^ punctuation.definition.generics.open.rbs
#                 ^ punctuation.definition.generics.close.rbs
#                   ^ keyword.other.end.rbs

module Baz : BasicObject, ::_Each
#          ^ punctuation.definition.module_self.colon.rbs
#            ^ variable.other.module_self.class.rbs
#                       ^ punctuation.separator.module_self.comma.rbs
#                         ^ punctuation.separator.type_name.root.rbs
#                           ^ variable.other.module_self.interface.rbs
  Foo: String
# ^ entity.name.constant.rbs
#    ^ punctuation.separator.colon.rbs
end
# keyword.other.end.rbs
